packages:
  - 'packages/*'
  - 'playground'
  - 'docs'

overrides:
  svelte2tsx: ^0.7.55

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@lucide/svelte@1.20.0'
  - '@sveltejs/kit@2.65.2'

onlyBuiltDependencies:
  - esbuild
