import type { WordItem } from '@shamokit/svelte-wordcloud';

export const FONT_URL =
	'https://cdn.jsdelivr.net/fontsource/fonts/m-plus-1p@5/japanese-400-normal.woff2';

export const words: WordItem[] = [
	{ word: 'Svelte', counts: 600, link: 'https://svelte.dev' },
	{ word: 'TypeScript', counts: 540, link: 'https://www.typescriptlang.org' },
	{ word: 'JavaScript', counts: 490, link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript' },
	{ word: 'React', counts: 440 },
	{ word: 'Vue', counts: 400 },
	{ word: 'Vite', counts: 370, link: 'https://vitejs.dev' },
	{ word: 'Node.js', counts: 340, link: 'https://nodejs.org' },
	{ word: 'Three.js', counts: 310, link: 'https://threejs.org' },
	{ word: 'WebGL', counts: 290 },
	{ word: 'Threlte', counts: 270, link: 'https://threlte.xyz' },
	{ word: 'CSS', counts: 260 },
	{ word: 'HTML', counts: 245 },
	{ word: 'SvelteKit', counts: 230, link: 'https://kit.svelte.dev' },
	{ word: 'Tailwind', counts: 220 },
	{ word: 'GraphQL', counts: 210, link: 'https://graphql.org' },
	{ word: 'REST API', counts: 200 },
	{ word: 'WebSockets', counts: 195 },
	{ word: 'Docker', counts: 190 },
	{ word: 'Git', counts: 185 },
	{ word: 'CI/CD', counts: 180 },
	{ word: 'Next.js', counts: 175 },
	{ word: 'Nuxt', counts: 170 },
	{ word: 'Astro', counts: 165, link: 'https://astro.build' },
	{ word: 'Remix', counts: 160 },
	{ word: 'Solid', counts: 158 },
	{ word: 'Qwik', counts: 155 },
	{ word: 'Angular', counts: 152 },
	{ word: 'WASM', counts: 150 },
	{ word: 'Vitest', counts: 148, link: 'https://vitest.dev' },
	{ word: 'Playwright', counts: 145 },
	{ word: 'pnpm', counts: 143, link: 'https://pnpm.io' },
	{ word: 'Bun', counts: 140, link: 'https://bun.sh' },
	{ word: 'Deno', counts: 138, link: 'https://deno.com' },
	{ word: 'ESLint', counts: 136 },
	{ word: 'Prettier', counts: 134 },
	{ word: 'Sass', counts: 132 },
	{ word: 'PostCSS', counts: 130 },
	{ word: 'tRPC', counts: 128 },
	{ word: 'Zod', counts: 126 },
	{ word: 'Prisma', counts: 124 },
	{ word: 'Drizzle', counts: 122 },
	{ word: 'Turborepo', counts: 120 },
	{ word: 'esbuild', counts: 118 },
	{ word: 'Rollup', counts: 116 },
	{ word: 'Webpack', counts: 114 },
	{ word: 'Supabase', counts: 112 },
	{ word: 'Firebase', counts: 110 },
	{ word: 'OpenAI', counts: 108 },
	{ word: 'Figma', counts: 106 },
	{ word: 'Storybook', counts: 104 },
	{ word: 'Cypress', counts: 102 },
	{ word: 'Jest', counts: 100 },
	{ word: 'Mocha', counts: 100 },
	{ word: 'GSAP', counts: 100 },
	{ word: 'Framer', counts: 100 },
	{ word: 'Lottie', counts: 100 },
	{ word: 'D3.js', counts: 100, link: 'https://d3js.org' },
	{ word: 'Chart.js', counts: 100 },
	{ word: 'Redux', counts: 100 },
	{ word: 'MobX', counts: 100 },
	{ word: 'Zustand', counts: 100 },
	{ word: 'Jotai', counts: 100 },
	{ word: 'Pinia', counts: 100 },
	{ word: 'Recoil', counts: 100 },
	{ word: 'XState', counts: 100 },
	{ word: 'Electron', counts: 100 },
	{ word: 'Tauri', counts: 100, link: 'https://tauri.app' },
	{ word: 'Capacitor', counts: 100 },
	{ word: 'React Native', counts: 100 },
	{ word: 'Flutter', counts: 100 },
	{ word: 'Swift', counts: 100 },
	{ word: 'Kotlin', counts: 100 },
	{ word: 'Rust', counts: 100 },
	{ word: 'Go', counts: 100 },
	{ word: 'Python', counts: 100 },
	{ word: 'MongoDB', counts: 100 },
	{ word: 'PostgreSQL', counts: 100 },
	{ word: 'Redis', counts: 100 },
	{ word: 'SQLite', counts: 100 },
	{ word: 'Cloudflare', counts: 100 },
	{ word: 'Vercel', counts: 100, link: 'https://vercel.com' },
	{ word: 'Netlify', counts: 100 },
	{ word: 'AWS', counts: 100 },
	{ word: 'GCP', counts: 100 },
	{ word: 'Azure', counts: 100 },
	{ word: 'Kubernetes', counts: 100 },
	{ word: 'Terraform', counts: 100 },
	{ word: 'Ansible', counts: 100 },
	{ word: 'Jenkins', counts: 100 },
	{ word: 'GitHub Actions', counts: 100 },
	{ word: 'Nginx', counts: 100 },
	{ word: 'Apache', counts: 100 },
	{ word: 'Linux', counts: 100 },
	{ word: 'Bash', counts: 100 },
	{ word: 'PowerShell', counts: 100 },
	{ word: 'SSH', counts: 100 },
	{ word: 'JWT', counts: 100 },
	{ word: 'OAuth', counts: 100 },
	{ word: 'WebRTC', counts: 100 },
	{ word: 'PWA', counts: 100 },
	{ word: 'Service Worker', counts: 100 },
	{ word: 'IndexedDB', counts: 100 },
	{ word: 'LocalStorage', counts: 100 },
	{ word: 'Canvas API', counts: 100 },
	{ word: 'Web Audio', counts: 100 },
	{ word: 'WebXR', counts: 100 },
	{ word: 'Babylon.js', counts: 100 },
	{ word: 'PixiJS', counts: 100 },
	{ word: 'Phaser', counts: 100 },
	{ word: 'Matter.js', counts: 100 },
	{ word: 'Rapier', counts: 100 },
	{ word: 'glTF', counts: 100 },
	{ word: 'GLSL', counts: 100 },
	{ word: 'HLSL', counts: 100 },
	{ word: 'OpenGL', counts: 100 },
	{ word: 'Vulkan', counts: 100 },
	{ word: 'Metal', counts: 100 },
	{ word: 'DirectX', counts: 100 },
	{ word: 'Unreal', counts: 100 },
	{ word: 'Unity', counts: 100 },
];

// ~600 words for heavy performance testing
export const heavyWords: WordItem[] = [
	{ word: 'JavaScript', counts: 990 },
	{ word: 'TypeScript', counts: 450 },
	{ word: 'Python', counts: 900 },
	{ word: 'Rust', counts: 150 },
	{ word: 'Go', counts: 165 },
	{ word: 'Java', counts: 175 },
	{ word: 'C++', counts: 140 },
	{ word: 'C#', counts: 135 },
	{ word: 'Swift', counts: 105 },
	{ word: 'Kotlin', counts: 100 },
	{ word: 'Ruby', counts: 90 },
	{ word: 'PHP', counts: 100 },
	{ word: 'Scala', counts: 65 },
	{ word: 'Haskell', counts: 55 },
	{ word: 'Elixir', counts: 60 },
	{ word: 'Clojure', counts: 55 },
	{ word: 'Erlang', counts: 50 },
	{ word: 'OCaml', counts: 50 },
	{ word: 'F#', counts: 48 },
	{ word: 'Dart', counts: 75 },
	{ word: 'React', counts: 500 },
	{ word: 'Svelte', counts: 230 },
	{ word: 'Vue', counts: 290 },
	{ word: 'Angular', counts: 155 },
	{ word: 'Solid', counts: 85 },
	{ word: 'Qwik', counts: 70 },
	{ word: 'Astro', counts: 130 },
	{ word: 'Remix', counts: 100 },
	{ word: 'Next.js', counts: 260 },
	{ word: 'Nuxt', counts: 155 },
	{ word: 'SvelteKit', counts: 195 },
	{ word: 'Gatsby', counts: 80 },
	{ word: 'Vite', counts: 230 },
	{ word: 'Webpack', counts: 175 },
	{ word: 'Rollup', counts: 90 },
	{ word: 'esbuild', counts: 110 },
	{ word: 'Parcel', counts: 70 },
	{ word: 'Turbopack', counts: 65 },
	{ word: 'Bun', counts: 145 },
	{ word: 'Deno', counts: 130 },
	{ word: 'Node.js', counts: 360 },
	{ word: 'pnpm', counts: 175 },
	{ word: 'Yarn', counts: 160 },
	{ word: 'npm', counts: 245 },
	{ word: 'Turborepo', counts: 80 },
	{ word: 'Nx', counts: 65 },
	{ word: 'Lerna', counts: 55 },
	{ word: 'Three.js', counts: 185 },
	{ word: 'Babylon.js', counts: 95 },
	{ word: 'WebGL', counts: 175 },
	{ word: 'WebGPU', counts: 120 },
	{ word: 'GLSL', counts: 80 },
	{ word: 'WGSL', counts: 65 },
	{ word: 'Threlte', counts: 75 },
	{ word: 'R3F', counts: 70 },
	{ word: 'PixiJS', counts: 85 },
	{ word: 'Phaser', counts: 80 },
	{ word: 'Matter.js', counts: 60 },
	{ word: 'Rapier', counts: 55 },
	{ word: 'Cannon.js', counts: 50 },
	{ word: 'Ammo.js', counts: 48 },
	{ word: 'D3.js', counts: 160 },
	{ word: 'Chart.js', counts: 140 },
	{ word: 'Recharts', counts: 80 },
	{ word: 'Highcharts', counts: 90 },
	{ word: 'Victory', counts: 65 },
	{ word: 'Nivo', counts: 60 },
	{ word: 'ApexCharts', counts: 55 },
	{ word: 'Visx', counts: 50 },
	{ word: 'PostgreSQL', counts: 275 },
	{ word: 'MySQL', counts: 215 },
	{ word: 'SQLite', counts: 185 },
	{ word: 'MongoDB', counts: 225 },
	{ word: 'Redis', counts: 255 },
	{ word: 'Cassandra', counts: 80 },
	{ word: 'CockroachDB', counts: 70 },
	{ word: 'DynamoDB', counts: 115 },
	{ word: 'Firestore', counts: 100 },
	{ word: 'Supabase', counts: 170 },
	{ word: 'PlanetScale', counts: 70 },
	{ word: 'Neon', counts: 75 },
	{ word: 'Turso', counts: 60 },
	{ word: 'ElasticSearch', counts: 120 },
	{ word: 'Prisma', counts: 155 },
	{ word: 'Drizzle', counts: 130 },
	{ word: 'Sequelize', counts: 80 },
	{ word: 'TypeORM', counts: 70 },
	{ word: 'Mongoose', counts: 90 },
	{ word: 'Kysely', counts: 60 },
	{ word: 'AWS', counts: 400 },
	{ word: 'GCP', counts: 185 },
	{ word: 'Azure', counts: 175 },
	{ word: 'Vercel', counts: 185 },
	{ word: 'Netlify', counts: 165 },
	{ word: 'Cloudflare', counts: 210 },
	{ word: 'Fly.io', counts: 95 },
	{ word: 'Railway', counts: 85 },
	{ word: 'Render', counts: 75 },
	{ word: 'DigitalOcean', counts: 100 },
	{ word: 'Heroku', counts: 110 },
	{ word: 'Kubernetes', counts: 340 },
	{ word: 'Docker', counts: 560 },
	{ word: 'Podman', counts: 75 },
	{ word: 'Terraform', counts: 165 },
	{ word: 'Pulumi', counts: 90 },
	{ word: 'Ansible', counts: 115 },
	{ word: 'Chef', counts: 60 },
	{ word: 'Puppet', counts: 55 },
	{ word: 'Helm', counts: 100 },
	{ word: 'Istio', counts: 75 },
	{ word: 'Linkerd', counts: 60 },
	{ word: 'Envoy', counts: 55 },
	{ word: 'GitHub Actions', counts: 280 },
	{ word: 'GitLab CI', counts: 160 },
	{ word: 'CircleCI', counts: 110 },
	{ word: 'Jenkins', counts: 150 },
	{ word: 'Travis CI', counts: 80 },
	{ word: 'Buildkite', counts: 65 },
	{ word: 'Drone CI', counts: 60 },
	{ word: 'ArgoCD', counts: 100 },
	{ word: 'Flux', counts: 80 },
	{ word: 'Spinnaker', counts: 55 },
	{ word: 'Git', counts: 750 },
	{ word: 'GitHub', counts: 330 },
	{ word: 'GitLab', counts: 210 },
	{ word: 'Bitbucket', counts: 115 },
	{ word: 'Gitea', counts: 70 },
	{ word: 'ESLint', counts: 230 },
	{ word: 'Prettier', counts: 215 },
	{ word: 'Biome', counts: 100 },
	{ word: 'Husky', counts: 85 },
	{ word: 'lint-staged', counts: 70 },
	{ word: 'Vitest', counts: 210 },
	{ word: 'Jest', counts: 200 },
	{ word: 'Mocha', counts: 120 },
	{ word: 'Jasmine', counts: 90 },
	{ word: 'Cypress', counts: 185 },
	{ word: 'Playwright', counts: 200 },
	{ word: 'Puppeteer', counts: 130 },
	{ word: 'Selenium', counts: 115 },
	{ word: 'WebdriverIO', counts: 75 },
	{ word: 'Storybook', counts: 170 },
	{ word: 'Chromatic', counts: 65 },
	{ word: 'Percy', counts: 60 },
	{ word: 'Applitools', counts: 55 },
	{ word: 'k6', counts: 90 },
	{ word: 'Locust', counts: 70 },
	{ word: 'Gatling', counts: 60 },
	{ word: 'Grafana', counts: 160 },
	{ word: 'Prometheus', counts: 155 },
	{ word: 'Datadog', counts: 145 },
	{ word: 'New Relic', counts: 115 },
	{ word: 'Sentry', counts: 185 },
	{ word: 'LogRocket', counts: 80 },
	{ word: 'OpenAI', counts: 210 },
	{ word: 'Anthropic', counts: 175 },
	{ word: 'Gemini', counts: 155 },
	{ word: 'Mistral', counts: 135 },
	{ word: 'LangChain', counts: 185 },
	{ word: 'LlamaIndex', counts: 120 },
	{ word: 'Ollama', counts: 140 },
	{ word: 'HuggingFace', counts: 165 },
	{ word: 'Pinecone', counts: 80 },
	{ word: 'Weaviate', counts: 75 },
	{ word: 'Qdrant', counts: 70 },
	{ word: 'Chroma', counts: 65 },
	{ word: 'FAISS', counts: 65 },
	{ word: 'TensorFlow', counts: 170 },
	{ word: 'PyTorch', counts: 165 },
	{ word: 'JAX', counts: 80 },
	{ word: 'scikit-learn', counts: 115 },
	{ word: 'pandas', counts: 150 },
	{ word: 'NumPy', counts: 165 },
	{ word: 'Polars', counts: 90 },
	{ word: 'DuckDB', counts: 85 },
	{ word: 'GraphQL', counts: 200 },
	{ word: 'REST', counts: 280 },
	{ word: 'tRPC', counts: 155 },
	{ word: 'gRPC', counts: 130 },
	{ word: 'WebSockets', counts: 195 },
	{ word: 'SSE', counts: 100 },
	{ word: 'WebRTC', counts: 125 },
	{ word: 'MQTT', counts: 90 },
	{ word: 'AMQP', counts: 70 },
	{ word: 'Kafka', counts: 165 },
	{ word: 'RabbitMQ', counts: 145 },
	{ word: 'NATS', counts: 65 },
	{ word: 'Pulsar', counts: 65 },
	{ word: 'Apollo', counts: 125 },
	{ word: 'Relay', counts: 85 },
	{ word: 'urql', counts: 70 },
	{ word: 'SWR', counts: 115 },
	{ word: 'TanStack Query', counts: 155 },
	{ word: 'Zod', counts: 200 },
	{ word: 'Yup', counts: 105 },
	{ word: 'Valibot', counts: 75 },
	{ word: 'Ajv', counts: 60 },
	{ word: 'Redux', counts: 200 },
	{ word: 'MobX', counts: 120 },
	{ word: 'Zustand', counts: 185 },
	{ word: 'Jotai', counts: 115 },
	{ word: 'Recoil', counts: 95 },
	{ word: 'XState', counts: 110 },
	{ word: 'Pinia', counts: 145 },
	{ word: 'Nanostores', counts: 70 },
	{ word: 'Immer', counts: 110 },
	{ word: 'Valtio', counts: 85 },
	{ word: 'Signals', counts: 95 },
	{ word: 'RxJS', counts: 125 },
	{ word: 'Effector', counts: 65 },
	{ word: 'Electron', counts: 155 },
	{ word: 'Tauri', counts: 140 },
	{ word: 'Neutralino', counts: 55 },
	{ word: 'Wails', counts: 50 },
	{ word: 'NW.js', counts: 50 },
	{ word: 'React Native', counts: 200 },
	{ word: 'Flutter', counts: 190 },
	{ word: 'Capacitor', counts: 95 },
	{ word: 'Expo', counts: 110 },
	{ word: 'Ionic', counts: 85 },
	{ word: 'CSS', counts: 820 },
	{ word: 'Tailwind', counts: 310 },
	{ word: 'Sass', counts: 225 },
	{ word: 'PostCSS', counts: 145 },
	{ word: 'CSS Modules', counts: 135 },
	{ word: 'styled-components', counts: 155 },
	{ word: 'Emotion', counts: 125 },
	{ word: 'Stitches', counts: 70 },
	{ word: 'vanilla-extract', counts: 80 },
	{ word: 'Panda CSS', counts: 75 },
	{ word: 'UnoCSS', counts: 90 },
	{ word: 'Bootstrap', counts: 200 },
	{ word: 'Material UI', counts: 185 },
	{ word: 'Chakra UI', counts: 150 },
	{ word: 'Radix UI', counts: 170 },
	{ word: 'shadcn/ui', counts: 195 },
	{ word: 'Headless UI', counts: 140 },
	{ word: 'Flowbite', counts: 75 },
	{ word: 'DaisyUI', counts: 120 },
	{ word: 'Mantine', counts: 110 },
	{ word: 'Ant Design', counts: 145 },
	{ word: 'Vuetify', counts: 105 },
	{ word: 'Quasar', counts: 85 },
	{ word: 'Skeleton', counts: 55 },
	{ word: 'HTML', counts: 680 },
	{ word: 'SVG', counts: 245 },
	{ word: 'Canvas API', counts: 200 },
	{ word: 'Web Audio', counts: 105 },
	{ word: 'WebXR', counts: 90 },
	{ word: 'WebAssembly', counts: 195 },
	{ word: 'PWA', counts: 175 },
	{ word: 'Service Worker', counts: 140 },
	{ word: 'IndexedDB', counts: 110 },
	{ word: 'Web Crypto', counts: 90 },
	{ word: 'Web Components', counts: 140 },
	{ word: 'Shadow DOM', counts: 100 },
	{ word: 'Custom Elements', counts: 85 },
	{ word: 'Intersection Observer', counts: 110 },
	{ word: 'ResizeObserver', counts: 95 },
	{ word: 'MutationObserver', counts: 85 },
	{ word: 'Broadcast Channel', counts: 65 },
	{ word: 'SharedArrayBuffer', counts: 60 },
	{ word: 'Web Workers', counts: 130 },
	{ word: 'Comlink', counts: 55 },
	{ word: 'OPFS', counts: 50 },
	{ word: 'JWT', counts: 260 },
	{ word: 'OAuth', counts: 250 },
	{ word: 'OpenID Connect', counts: 130 },
	{ word: 'SAML', counts: 100 },
	{ word: 'Passkeys', counts: 100 },
	{ word: 'Auth.js', counts: 140 },
	{ word: 'Clerk', counts: 155 },
	{ word: 'Auth0', counts: 175 },
	{ word: 'Okta', counts: 125 },
	{ word: 'Keycloak', counts: 95 },
	{ word: 'Supertokens', counts: 75 },
	{ word: 'Better Auth', counts: 75 },
	{ word: 'Lucia', counts: 70 },
	{ word: 'bcrypt', counts: 115 },
	{ word: 'argon2', counts: 90 },
	{ word: 'CSRF', counts: 185 },
	{ word: 'CORS', counts: 215 },
	{ word: 'CSP', counts: 120 },
	{ word: 'HTTPS', counts: 260 },
	{ word: 'TLS', counts: 155 },
	{ word: 'Nginx', counts: 130 },
	{ word: 'Caddy', counts: 80 },
	{ word: 'Traefik', counts: 70 },
	{ word: 'Figma', counts: 330 },
	{ word: 'Sketch', counts: 120 },
	{ word: 'Adobe XD', counts: 110 },
	{ word: 'Framer', counts: 175 },
	{ word: 'Penpot', counts: 90 },
	{ word: 'Zeplin', counts: 80 },
	{ word: 'Lottie', counts: 150 },
	{ word: 'GSAP', counts: 215 },
	{ word: 'Motion', counts: 130 },
	{ word: 'Anime.js', counts: 100 },
	{ word: 'Popmotion', counts: 70 },
	{ word: 'Spring', counts: 85 },
	{ word: 'CSS Animation', counts: 170 },
	{ word: 'CSS Transition', counts: 160 },
	{ word: 'View Transitions', counts: 115 },
	{ word: 'Hono', counts: 160 },
	{ word: 'Express', counts: 310 },
	{ word: 'Fastify', counts: 210 },
	{ word: 'Koa', counts: 120 },
	{ word: 'NestJS', counts: 205 },
	{ word: 'Elysia', counts: 95 },
	{ word: 'Nitro', counts: 100 },
	{ word: 'H3', counts: 80 },
	{ word: 'Oak', counts: 65 },
	{ word: 'Fresh', counts: 75 },
	{ word: 'Gin', counts: 155 },
	{ word: 'Fiber', counts: 120 },
	{ word: 'Echo', counts: 110 },
	{ word: 'Actix', counts: 110 },
	{ word: 'Axum', counts: 105 },
	{ word: 'Rocket', counts: 90 },
	{ word: 'Phoenix', counts: 145 },
	{ word: 'Rails', counts: 160 },
	{ word: 'Django', counts: 235 },
	{ word: 'FastAPI', counts: 225 },
	{ word: 'Flask', counts: 180 },
	{ word: 'Spring Boot', counts: 175 },
	{ word: 'Quarkus', counts: 60 },
	{ word: 'OpenTelemetry', counts: 200 },
	{ word: 'Jaeger', counts: 105 },
	{ word: 'Zipkin', counts: 85 },
	{ word: 'Loki', counts: 115 },
	{ word: 'Victoria Metrics', counts: 70 },
	{ word: 'InfluxDB', counts: 95 },
	{ word: 'Splunk', counts: 120 },
	{ word: 'Elastic APM', counts: 90 },
	{ word: 'PagerDuty', counts: 105 },
	{ word: 'OpsGenie', counts: 80 },
	{ word: 'Linear', counts: 175 },
	{ word: 'Jira', counts: 225 },
	{ word: 'Notion', counts: 265 },
	{ word: 'Confluence', counts: 155 },
	{ word: 'Slack', counts: 305 },
	{ word: 'Discord', counts: 280 },
	{ word: 'Loom', counts: 115 },
	{ word: 'Postman', counts: 215 },
	{ word: 'Insomnia', counts: 115 },
	{ word: 'Bruno', counts: 90 },
	{ word: 'Swagger', counts: 165 },
	{ word: 'OpenAPI', counts: 150 },
	{ word: 'AsyncAPI', counts: 70 },
	{ word: 'glTF', counts: 125 },
	{ word: 'HLSL', counts: 105 },
	{ word: 'OpenGL', counts: 150 },
	{ word: 'Vulkan', counts: 120 },
	{ word: 'Metal', counts: 100 },
	{ word: 'DirectX', counts: 110 },
	{ word: 'Unreal', counts: 195 },
	{ word: 'Unity', counts: 240 },
	{ word: 'Godot', counts: 175 },
	{ word: 'Bevy', counts: 110 },
	{ word: 'MonoGame', counts: 65 },
	{ word: 'SFML', counts: 65 },
	{ word: 'SDL', counts: 80 },
	{ word: 'OpenAL', counts: 55 },
	{ word: 'FMOD', counts: 65 },
	{ word: 'Wwise', counts: 55 },
	{ word: 'Spine', counts: 55 },
	{ word: 'Tiled', counts: 50 },
	{ word: 'LDtk', counts: 50 },
	{ word: 'Aseprite', counts: 70 },
	{ word: 'Blender', counts: 165 },
	{ word: 'Maya', counts: 115 },
	{ word: 'ZBrush', counts: 75 },
	// More programming concepts and tools
	{ word: 'Microservices', counts: 225 },
	{ word: 'Monolith', counts: 125 },
	{ word: 'Serverless', counts: 205 },
	{ word: 'Edge Computing', counts: 140 },
	{ word: 'Event Sourcing', counts: 110 },
	{ word: 'CQRS', counts: 115 },
	{ word: 'DDD', counts: 140 },
	{ word: 'Hexagonal', counts: 85 },
	{ word: 'Clean Arch', counts: 110 },
	{ word: 'SOLID', counts: 165 },
	{ word: 'TDD', counts: 180 },
	{ word: 'BDD', counts: 120 },
	{ word: 'DRY', counts: 150 },
	{ word: 'KISS', counts: 135 },
	{ word: 'YAGNI', counts: 115 },
	{ word: 'Refactoring', counts: 160 },
	{ word: 'Code Review', counts: 205 },
	{ word: 'Pair Programming', counts: 130 },
	{ word: 'Mob Programming', counts: 80 },
	{ word: 'Trunk Based Dev', counts: 70 },
	// Web platform
	{ word: 'HTTP/2', counts: 255 },
	{ word: 'HTTP/3', counts: 210 },
	{ word: 'QUIC', counts: 115 },
	{ word: 'TCP', counts: 230 },
	{ word: 'UDP', counts: 100 },
	{ word: 'DNS', counts: 220 },
	{ word: 'CDN', counts: 255 },
	{ word: 'Load Balancer', counts: 175 },
	{ word: 'Reverse Proxy', counts: 145 },
	{ word: 'API Gateway', counts: 165 },
	{ word: 'WAF', counts: 105 },
	{ word: 'DDoS', counts: 115 },
	{ word: 'Rate Limiting', counts: 135 },
	{ word: 'Circuit Breaker', counts: 125 },
	{ word: 'Retry Logic', counts: 100 },
	{ word: 'Backpressure', counts: 80 },
	{ word: 'Bulkhead', counts: 70 },
	{ word: 'Timeout', counts: 110 },
	{ word: 'Idempotency', counts: 90 },
	{ word: 'Pagination', counts: 145 },
	// Data formats and protocols
	{ word: 'JSON', counts: 620 },
	{ word: 'YAML', counts: 340 },
	{ word: 'TOML', counts: 165 },
	{ word: 'XML', counts: 205 },
	{ word: 'Protocol Buffers', counts: 160 },
	{ word: 'MessagePack', counts: 105 },
	{ word: 'Avro', counts: 90 },
	{ word: 'Parquet', counts: 130 },
	{ word: 'Arrow', counts: 100 },
	{ word: 'CSV', counts: 215 },
	{ word: 'Markdown', counts: 310 },
	{ word: 'MDX', counts: 135 },
	{ word: 'LaTeX', counts: 110 },
	// Security
	{ word: 'Zero Trust', counts: 195 },
	{ word: 'SOC 2', counts: 160 },
	{ word: 'GDPR', counts: 240 },
	{ word: 'HIPAA', counts: 175 },
	{ word: 'PCI DSS', counts: 140 },
	{ word: 'Encryption', counts: 270 },
	{ word: 'AES', counts: 135 },
	{ word: 'RSA', counts: 125 },
	{ word: 'ECDSA', counts: 90 },
	{ word: 'Ed25519', counts: 85 },
	{ word: 'SHA-256', counts: 125 },
	{ word: 'SHA-3', counts: 95 },
	{ word: 'BLAKE3', counts: 75 },
	{ word: 'Vault', counts: 155 },
	{ word: 'SOPS', counts: 80 },
	{ word: 'Sealed Secrets', counts: 70 },
	{ word: 'Snyk', counts: 125 },
	{ word: 'Trivy', counts: 105 },
	{ word: 'OWASP', counts: 185 },
	{ word: 'CVE', counts: 125 },
	{ word: 'Pen Testing', counts: 95 },
	// Platform engineering
	{ word: 'Platform Eng', counts: 175 },
	{ word: 'GitOps', counts: 190 },
	{ word: 'DevSecOps', counts: 165 },
	{ word: 'SRE', counts: 215 },
	{ word: 'SLO', counts: 140 },
	{ word: 'SLI', counts: 120 },
	{ word: 'SLA', counts: 145 },
	{ word: 'MTTR', counts: 100 },
	{ word: 'MTTD', counts: 90 },
	{ word: 'Incident Mgmt', counts: 130 },
	{ word: 'Runbook', counts: 100 },
	{ word: 'Postmortem', counts: 115 },
	{ word: 'On-call', counts: 110 },
	{ word: 'Feature Flags', counts: 185 },
	{ word: 'A/B Testing', counts: 205 },
	{ word: 'Canary Deploy', counts: 130 },
	{ word: 'Blue-Green', counts: 115 },
	{ word: 'Shadow Traffic', counts: 75 },
	{ word: 'Chaos Eng', counts: 95 },
	{ word: 'Load Testing', counts: 135 },
	// Emerging tech
	{ word: 'Web3', counts: 170 },
	{ word: 'Blockchain', counts: 195 },
	{ word: 'IPFS', counts: 95 },
	{ word: 'Ethereum', counts: 165 },
	{ word: 'Solana', counts: 110 },
	{ word: 'Solidity', counts: 125 },
	{ word: 'Move', counts: 70 },
	{ word: 'Zero-Knowledge', counts: 130 },
	{ word: 'Homomorphic', counts: 55 },
	{ word: 'Federated ML', counts: 65 },
	{ word: 'Edge AI', counts: 110 },
	{ word: 'ONNX', counts: 115 },
	{ word: 'CoreML', counts: 95 },
	{ word: 'TensorRT', counts: 100 },
	{ word: 'triton', counts: 65 },
	{ word: 'CUDA', counts: 210 },
	{ word: 'ROCm', counts: 60 },
	{ word: 'WebNN', counts: 75 },
	{ word: 'Transformers.js', counts: 90 },
	{ word: 'MediaPipe', counts: 90 },
	// Developer experience
	{ word: 'LSP', counts: 175 },
	{ word: 'DAP', counts: 90 },
	{ word: 'tree-sitter', counts: 105 },
	{ word: 'Neovim', counts: 240 },
	{ word: 'VS Code', counts: 380 },
	{ word: 'JetBrains', counts: 215 },
	{ word: 'Zed', counts: 140 },
	{ word: 'Helix', counts: 105 },
	{ word: 'Emacs', counts: 115 },
	{ word: 'Vim', counts: 205 },
	{ word: 'tmux', counts: 165 },
	{ word: 'Warp', counts: 125 },
	{ word: 'Ghostty', counts: 100 },
	{ word: 'Starship', counts: 135 },
	{ word: 'Oh My Zsh', counts: 145 },
	{ word: 'Fish', counts: 125 },
	{ word: 'Nushell', counts: 95 },
	{ word: 'Atuin', counts: 75 },
	{ word: 'zoxide', counts: 75 },
	{ word: 'fzf', counts: 140 },
	{ word: 'ripgrep', counts: 160 },
	{ word: 'bat', counts: 105 },
	{ word: 'fd', counts: 70 },
	{ word: 'eza', counts: 55 },
	// Package managers and runtimes
	{ word: 'Nix', counts: 195 },
	{ word: 'Homebrew', counts: 260 },
	{ word: 'apt', counts: 245 },
	{ word: 'pacman', counts: 125 },
	{ word: 'winget', counts: 110 },
	{ word: 'scoop', counts: 85 },
	{ word: 'asdf', counts: 115 },
	{ word: 'mise', counts: 95 },
	{ word: 'pyenv', counts: 150 },
	{ word: 'rbenv', counts: 100 },
	{ word: 'nvm', counts: 195 },
	{ word: 'fnm', counts: 115 },
	{ word: 'volta', counts: 105 },
	{ word: 'cargo', counts: 215 },
	{ word: 'pip', counts: 285 },
	{ word: 'uv', counts: 145 },
	{ word: 'poetry', counts: 145 },
	{ word: 'conda', counts: 175 },
	{ word: 'maven', counts: 150 },
	{ word: 'gradle', counts: 145 },
	{ word: 'bazel', counts: 95 },
	{ word: 'buck2', counts: 70 },
	{ word: 'pants', counts: 60 },
	// Observability
	{ word: 'Traces', counts: 215 },
	{ word: 'Metrics', counts: 250 },
	{ word: 'Logs', counts: 305 },
	{ word: 'Spans', counts: 130 },
	{ word: 'Sampling', counts: 115 },
	{ word: 'Baggage', counts: 80 },
	{ word: 'Profiling', counts: 165 },
	{ word: 'Flame Graphs', counts: 145 },
	{ word: 'Heap Dump', counts: 100 },
	{ word: 'Thread Dump', counts: 90 },
	{ word: 'Continuous Profiling', counts: 90 },
	{ word: 'Pyroscope', counts: 110 },
	{ word: 'Parca', counts: 85 },
	{ word: 'Clinic.js', counts: 75 },
	{ word: 'perf', counts: 130 },
	{ word: 'eBPF', counts: 185 },
	{ word: 'BCC', counts: 65 },
	{ word: 'bpftrace', counts: 60 },
	{ word: 'strace', counts: 85 },
];
