import type { WordItem } from '@shamokit/svelte-wordcloud';

export const FONT_URL =
	'https://fonts.gstatic.com/s/notosansjp/v56/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEj75s.ttf';

export const words: WordItem[] = [
	{ word: 'Svelte', counts: 600, link: 'https://svelte.dev' },
	{ word: 'TypeScript', counts: 540, link: 'https://www.typescriptlang.org' },
	{ word: 'JavaScript', counts: 490, link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript' },
	{ word: 'React', counts: 440 },
	{ word: 'Vue', counts: 400 },
	{ word: 'Vite', counts: 370, link: 'https://vitejs.dev' },
	{ word: 'Node.js', counts: 340, link: 'https://nodejs.org' },
	{ word: 'Three.js', counts: 310, link: 'https://threejs.org' },
	{ word: 'WebGL', counts: 290 },
	{ word: 'Threlte', counts: 270, link: 'https://threlte.xyz' },
	{ word: 'CSS', counts: 260 },
	{ word: 'HTML', counts: 245 },
	{ word: 'SvelteKit', counts: 230, link: 'https://kit.svelte.dev' },
	{ word: 'Tailwind', counts: 220 },
	{ word: 'GraphQL', counts: 210, link: 'https://graphql.org' },
	{ word: 'REST API', counts: 200 },
	{ word: 'WebSockets', counts: 195 },
	{ word: 'Docker', counts: 190 },
	{ word: 'Git', counts: 185 },
	{ word: 'CI/CD', counts: 180 },
	{ word: 'Next.js', counts: 175 },
	{ word: 'Nuxt', counts: 170 },
	{ word: 'Astro', counts: 165, link: 'https://astro.build' },
	{ word: 'Remix', counts: 160 },
	{ word: 'Solid', counts: 158 },
	{ word: 'Qwik', counts: 155 },
	{ word: 'Angular', counts: 152 },
	{ word: 'WASM', counts: 150 },
	{ word: 'Vitest', counts: 148, link: 'https://vitest.dev' },
	{ word: 'Playwright', counts: 145 },
	{ word: 'pnpm', counts: 143, link: 'https://pnpm.io' },
	{ word: 'Bun', counts: 140, link: 'https://bun.sh' },
	{ word: 'Deno', counts: 138, link: 'https://deno.com' },
	{ word: 'ESLint', counts: 136 },
	{ word: 'Prettier', counts: 134 },
	{ word: 'Sass', counts: 132 },
	{ word: 'PostCSS', counts: 130 },
	{ word: 'tRPC', counts: 128 },
	{ word: 'Zod', counts: 126 },
	{ word: 'Prisma', counts: 124 },
	{ word: 'Drizzle', counts: 122 },
	{ word: 'Turborepo', counts: 120 },
	{ word: 'esbuild', counts: 118 },
	{ word: 'Rollup', counts: 116 },
	{ word: 'Webpack', counts: 114 },
	{ word: 'Supabase', counts: 112 },
	{ word: 'Firebase', counts: 110 },
	{ word: 'OpenAI', counts: 108 },
	{ word: 'Figma', counts: 106 },
	{ word: 'Storybook', counts: 104 },
	{ word: 'Cypress', counts: 102 },
	{ word: 'Jest', counts: 100 },
	{ word: 'Mocha', counts: 100 },
	{ word: 'GSAP', counts: 100 },
	{ word: 'Framer', counts: 100 },
	{ word: 'Lottie', counts: 100 },
	{ word: 'D3.js', counts: 100, link: 'https://d3js.org' },
	{ word: 'Chart.js', counts: 100 },
	{ word: 'Redux', counts: 100 },
	{ word: 'MobX', counts: 100 },
	{ word: 'Zustand', counts: 100 },
	{ word: 'Jotai', counts: 100 },
	{ word: 'Pinia', counts: 100 },
	{ word: 'Recoil', counts: 100 },
	{ word: 'XState', counts: 100 },
	{ word: 'Electron', counts: 100 },
	{ word: 'Tauri', counts: 100, link: 'https://tauri.app' },
	{ word: 'Capacitor', counts: 100 },
	{ word: 'React Native', counts: 100 },
	{ word: 'Flutter', counts: 100 },
	{ word: 'Swift', counts: 100 },
	{ word: 'Kotlin', counts: 100 },
	{ word: 'Rust', counts: 100 },
	{ word: 'Go', counts: 100 },
	{ word: 'Python', counts: 100 },
	{ word: 'MongoDB', counts: 100 },
	{ word: 'PostgreSQL', counts: 100 },
	{ word: 'Redis', counts: 100 },
	{ word: 'SQLite', counts: 100 },
	{ word: 'Cloudflare', counts: 100 },
	{ word: 'Vercel', counts: 100, link: 'https://vercel.com' },
	{ word: 'Netlify', counts: 100 },
	{ word: 'AWS', counts: 100 },
	{ word: 'GCP', counts: 100 },
	{ word: 'Azure', counts: 100 },
	{ word: 'Kubernetes', counts: 100 },
	{ word: 'Terraform', counts: 100 },
	{ word: 'Ansible', counts: 100 },
	{ word: 'Jenkins', counts: 100 },
	{ word: 'GitHub Actions', counts: 100 },
	{ word: 'Nginx', counts: 100 },
	{ word: 'Apache', counts: 100 },
	{ word: 'Linux', counts: 100 },
	{ word: 'Bash', counts: 100 },
	{ word: 'PowerShell', counts: 100 },
	{ word: 'SSH', counts: 100 },
	{ word: 'JWT', counts: 100 },
	{ word: 'OAuth', counts: 100 },
	{ word: 'WebRTC', counts: 100 },
	{ word: 'PWA', counts: 100 },
	{ word: 'Service Worker', counts: 100 },
	{ word: 'IndexedDB', counts: 100 },
	{ word: 'LocalStorage', counts: 100 },
	{ word: 'Canvas API', counts: 100 },
	{ word: 'Web Audio', counts: 100 },
	{ word: 'WebXR', counts: 100 },
	{ word: 'Babylon.js', counts: 100 },
	{ word: 'PixiJS', counts: 100 },
	{ word: 'Phaser', counts: 100 },
	{ word: 'Matter.js', counts: 100 },
	{ word: 'Rapier', counts: 100 },
	{ word: 'glTF', counts: 100 },
	{ word: 'GLSL', counts: 100 },
	{ word: 'HLSL', counts: 100 },
	{ word: 'OpenGL', counts: 100 },
	{ word: 'Vulkan', counts: 100 },
	{ word: 'Metal', counts: 100 },
	{ word: 'DirectX', counts: 100 },
	{ word: 'Unreal', counts: 100 },
	{ word: 'Unity', counts: 100 },
];
